### PR TITLE
fix: encoding of mixed case enumerations (#15)

### LINKED ISSUE #15: pbjson does not support enum variants with lower case names
The following Protobuf message:

```
message Aggregate {
  enum AggregateType {
    AggregateTypeNone = 0;
    AggregateTypeSum = 1;
    AggregateTypeCount = 2;
    AggregateTypeMin = 3;
    AggregateTypeMax = 4;
    AggregateTypeFirst = 5;
    AggregateTypeLast = 6;
    AggregateTypeMean = 7;
  }

  AggregateType type = 1;

  // additional arguments?
}
```

Cannot be handled by `pbjson`; it complains with the following:

```
 thread 'main' panicked at 'illegal variant - AggregateTypeNone', /Users/edd/.cargo/registry/src/github.com-1ecc6299db9ec823/pbjson-build-0.1.0/src/generator.rs:52:9
```

### PR DESCRIPTION
**Pull request by tustvold**
The current logic to handle enumerations will never generate incorrect serialization code, but will panic if the protobuf definition contains lower case characters. This PR fixes that, and also adds in the ability to disable enum prefix stripping, a feature which prost also has.

The [protobuf spec](https://developers.google.com/protocol-buffers/docs/proto3#json) says that enum variants be encoded as-is in the proto definitions, and so that is what this PR does. If your proto definition has mixed capitalisation, so will your JSON payloads.

This must also follow the same logic used by prost to [strip enum prefixes](https://github.com/tokio-rs/prost/blob/d45a37cab69c2a0cda36a97df8823fcaf43dc1fe/prost-build/src/code_generator.rs#L998) to ensure we generate correct code.

Closes #15

### CODE REVIEW

File: pbjson-build/src/resolver.rs [hunk 1]
```diff
@@ -172,4 +175,29 @@ mod tests {
...
+        let package = Package::new("test.syntax3");
+        let resolver = Resolver::new(&[], &package, false);
+
+        let tests = [
+            ("MyEnum", "MyEnumFoo", "Foo"),
+            ("MyEnum", "MyEnumfoo", "MyEnumfoo"),
+            ("MyEnum", "MY_ENUM_foo", "Foo"),
+        ];
+
+        for (enumeration, variant, expected) in tests {
```
Comment (alamb) [inline pbjson-build/src/resolver.rs:190]: 👍

File: pbjson-test/src/lib.rs [hunk 2]
```diff
@@ -294,5 +295,17 @@ mod tests {
             nanos: 5049,
         });
         verify(&decoded, r#"{"duration":"40502002.000005049s"}"#);
+
+        decoded.duration = None;
```
Comment (alamb) [inline pbjson-test/src/lib.rs:299]: 👍  the tests look good to me.

**Review by alamb — APPROVED** [review]
Looks good to me (though I am not sure I am the best qualified to approve this PR_
