### PR TITLE
feat: fix resolver (#9)

### LINKED ISSUE #9: Issue when using types from different paths?
First of all, thanks for providing this package :+1: 

I'm trying to use this package together with `tonic_build` (which is using `prost_build`), and this works well when all types are within the same path (so far I've only tested the code generation path). However, I'm running into issues when some types within different paths.

Example directory layout:

```
api.proto
common/common.proto
```

When `api.proto` uses a type (in my case `Region`) from `common/proto.proto`, the generated pbjson code should have the appropriate prefix. For `tonic_build`, I manually configure this using, and this works well:

```rust
.extern_path(".common", "crate::common")
```

However, for `pbjson_build` no such method exist (I believe) and the code generator is assuming all imported types exist within the same scope, resulting in for example the following error:

```
3769 |             let v = Region::from_i32(self.region)                                                                                                    
     |                     ^^^^^^ not found in this scope                                                                                                   
     |                                                                                                                                                      
help: consider importing this enum                                                                                                                          
     |                                                                                                                                                      
6    | use crate::common::Region;
```

Is this indeed a feature that is missing, or is there something that I'm missing?

### PR DESCRIPTION
**Pull request by tustvold**
This adds support for extern_types, whilst also fixing a bug in the type resolution that would cause invalid code generation for field serializers of enumerations defined in different packages.

Closes #9

### CODE REVIEW

File: pbjson-build/src/generator.rs [hunk 1]
```diff
@@ -24,51 +21,6 @@ impl Display for Indent {
     }
 }
 
-#[derive(Debug)]
-pub struct Config {
```
Comment (tustvold) [inline pbjson-build/src/generator.rs:28]: This was moved and renamed to Resolver, to better reflect what it is

File: pbjson-build/src/resolver.rs [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+    /// Creates a new resolver for `package`
+    pub fn new(extern_types: &'a [(String, String)], package: &'a Package) -> Self {
+        Resolver {
+            extern_types,
+            package,
+        }
+    }
+
+    /// Lookup an extern type, returns the rust type followed by the remaining
+    /// number of path segments to skip
```
Comment (crepererum) [inline pbjson-build/src/resolver.rs:19]:
```suggestion
    /// Lookup an extern type, returns the rust type followed by the
    /// number of leading path segments to skip (they are already included in the rust type)
```

**Review by crepererum — APPROVED** [review]

File: pbjson-build/src/resolver.rs [hunk 3]
```diff
@@ -0,0 +1,175 @@
...
+        let (_, rust_path) = &self.extern_types[match_idx?];
+
+        if match_len == path.len() {
+            Some((rust_path.clone(), match_len))
+        } else {
+            Some((format!("{}::", rust_path), match_len))
+        }
+    }
+
+    /// Returns the rust type for `path` relative to `cur`
```
[the remark this answers is not in the document]
Comment (tustvold) [reply pbjson-build/src/resolver.rs:43]: Outdated comment, will fix :+1:
